# Generated by kpex 0.3.12
crashbackups stop
drc off
gds read /foss/designs/lab2/klayout/DAC_CORE_5bit.gds
load DAC_CORE_5bit
select top cell
flatten DAC_CORE_5bit_flat
load DAC_CORE_5bit_flat
cellname delete DAC_CORE_5bit -noprompt
cellname rename DAC_CORE_5bit_flat DAC_CORE_5bit
select top cell
extract path /foss/designs/lab2/klayout/output/DAC_CORE_5bit__DAC_CORE_5bit/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/lab2/klayout/output/DAC_CORE_5bit__DAC_CORE_5bit/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/lab2/klayout/output/DAC_CORE_5bit__DAC_CORE_5bit/magic_RC -o /foss/designs/lab2/klayout/output/DAC_CORE_5bit__DAC_CORE_5bit/magic_RC/DAC_CORE_5bit.pex.spice
quit -noprompt
